export type Lead = {id:string; company:string; website:string; industry:string; city:string; country:string; employees:number|null; email:string; source:string; created_at?:string};
export type Profile = {industry:string; country:string; min:number; max:number};
export const defaultProfile:Profile={industry:'IT Services',country:'United States',min:10,max:200};
export function domain(value:string){try{const u=new URL(/^https?:\/\//i.test(value)?value:'https://'+value);return /^https?:$/.test(u.protocol)&&u.hostname.includes('.')?u.hostname.toLowerCase().replace(/^www\./,''):'';}catch{return '';}}
export function emailValid(value:string){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);}
export function quality(l:Lead){const issues:string[]=[];if(!domain(l.website))issues.push('Missing or invalid website');if(!l.email)issues.push('Missing business email');else if(!emailValid(l.email))issues.push('Invalid email format');if(l.employees===null)issues.push('Unknown company size');if(!l.industry)issues.push('Missing industry');if(!l.country)issues.push('Missing country');return issues;}
export function score(l:Lead,p:Profile){const eq=(a:string,b:string)=>a.toLowerCase().trim()===b.toLowerCase().trim();const reasons=[{label:'Industry match',points:!p.industry||eq(l.industry,p.industry)?35:0,max:35},{label:'Country match',points:!p.country||eq(l.country,p.country)?25:0,max:25},{label:'Company size match',points:l.employees!==null&&l.employees>=p.min&&l.employees<=p.max?20:0,max:20},{label:'Email format',points:emailValid(l.email)?10:0,max:10},{label:'Website provided',points:domain(l.website)?10:0,max:10}];return {total:reasons.reduce((n,r)=>n+r.points,0),reasons};}
export function dedupKey(l:Lead){const d=domain(l.website);return d?'domain:'+d:'company:'+JSON.stringify([l.company,l.city,l.country].map(s=>s.toLowerCase().replace(/\s+/g,' ').trim()));}
export function parseCsv(input:string):string[][]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false,closed=false;input=input.replace(/^\uFEFF/,'');for(let i=0;i<input.length;i++){const c=input[i];if(quoted){if(c==='"'){if(input[i+1]==='"'){cell+='"';i++;}else{quoted=false;closed=true;}}else cell+=c;}else if(c==='"'){if(cell||closed)throw new Error('Unexpected quote in CSV');quoted=true;}else if(c===','){row.push(cell.trim());cell='';closed=false;}else if(c==='\n'||c==='\r'){if(c==='\r'&&input[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell='';closed=false;}else{if(closed&&c.trim())throw new Error('Unexpected text after quoted field');if(!closed)cell+=c;}}if(quoted)throw new Error('CSV contains an unclosed quote');row.push(cell.trim());if(row.some(Boolean))rows.push(row);return rows;}
export function importRows(csv:string){const rows=parseCsv(csv);if(rows.length<2)throw new Error('Add a header and at least one company row.');const headers=rows.shift()!.map(s=>s.toLowerCase().replace(/[ -]/g,'_'));if(!headers.includes('company'))throw new Error('The CSV needs a company column. Download the template for the supported columns.');if(new Set(headers).size!==headers.length)throw new Error('CSV headers must be unique.');if(rows.length>1000)throw new Error('Import up to 1,000 rows at a time.');let rejected=0;const leads:Lead[]=[];for(const r of rows){if(r.length!==headers.length||r.some(v=>v.length>500)){rejected++;continue;}const o=Object.fromEntries(headers.map((h,i)=>[h,r[i]]));if(!o.company){rejected++;continue;}const n=Number(o.employees);leads.push({id:crypto.randomUUID(),company:o.company,website:o.website||'',industry:o.industry||'',city:o.city||'',country:o.country||'',employees:o.employees&&Number.isInteger(n)&&n>=0&&n<=100000000?n:null,email:(o.email||'').toLowerCase(),source:o.source||'CSV import'});}return {leads,rejected,total:rows.length};}
export function exportCsv(leads:Lead[],p:Profile){const safe=(v:unknown)=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,m=>"'"+m).replace(/"/g,'""')+'"';const headers=['company','website','industry','city','country','employees','email','source','score','quality_issues'];return [headers.join(','),...leads.map(l=>[l.company,l.website,l.industry,l.city,l.country,l.employees,l.email,l.source,score(l,p).total,quality(l).join('; ')].map(safe).join(','))].join('\r\n');}
