'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Search, SlidersHorizontal, Download, Upload, Building2, Check, X, ChevronRight, Target, Database, ShieldCheck, AlertCircle, FileSpreadsheet, ArrowUpRight, Layers, RefreshCw } from 'lucide-react';
import { defaultProfile, domain, exportCsv, quality, score, type Lead, type Profile } from '../lib/leads';
type Report={inserted:number;duplicates:number;rejected:number;total:number};
export default function Home(){
 const [leads,setLeads]=useState<Lead[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [profile,setProfile]=useState<Profile>(defaultProfile),[query,setQuery]=useState(''),[view,setView]=useState('all'),[selected,setSelected]=useState<Set<string>>(new Set()),[detail,setDetail]=useState<Lead|null>(null),[importOpen,setImportOpen]=useState(false),[report,setReport]=useState<Report|null>(null),[sort,setSort]=useState('score');
 const file=useRef<HTMLInputElement>(null);const closeButton=useRef<HTMLButtonElement>(null);
 async function load(){setLoading(true);try{const r=await fetch('/api/leads');const d=await r.json() as {error?:string;leads:Lead[]};if(!r.ok)throw new Error(d.error);setLeads(d.leads);}catch(e){setError(e instanceof Error?e.message:'Unable to load leads.');}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 useEffect(()=>{if(detail||importOpen){closeButton.current?.focus();const fn=(e:KeyboardEvent)=>{if(e.key==='Escape'){setDetail(null);setImportOpen(false);}if(e.key==='Tab'){const dialog=document.querySelector('[role=dialog]');const els=dialog?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),select');if(els?.length){const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}};document.addEventListener('keydown',fn);return()=>document.removeEventListener('keydown',fn);}},[detail,importOpen]);
 const filtered=useMemo(()=>leads.filter(l=>{const s=score(l,profile).total;return (!query||[l.company,l.industry,l.city,l.country,l.website].join(' ').toLowerCase().includes(query.toLowerCase()))&&(view==='all'||view==='priority'&&s>=80||view==='review'&&quality(l).length>0);}).sort((a,b)=>sort==='company'?a.company.localeCompare(b.company):score(b,profile).total-score(a,profile).total||a.company.localeCompare(b.company)),[leads,profile,query,view,sort]);
 const high=leads.filter(l=>score(l,profile).total>=80).length,review=leads.filter(l=>quality(l).length).length;
 async function importCsv(csv:string){setBusy(true);setError('');try{const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'text/csv'},body:csv});const d=await r.json() as Report & {error?:string};if(!r.ok)throw new Error(d.error);setReport(d);setImportOpen(false);await load();}catch(e){setError(e instanceof Error?e.message:'Import failed.');}finally{setBusy(false);}}
 async function sample(){try{const r=await fetch('/sample-leads.csv');if(!r.ok)throw new Error('Sample could not be loaded.');await importCsv(await r.text());}catch(e){setError(String(e));}}
 function download(){const data=selected.size?filtered.filter(l=>selected.has(l.id)):filtered;const url=URL.createObjectURL(new Blob([exportCsv(data,profile)],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='leadlens-shortlist.csv';a.click();URL.revokeObjectURL(url);setNotice(`${data.length} leads exported with scores and quality notes.`);}
 const toggle=(id:string)=>setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n;});
 const changeProfile=(key:keyof Profile,value:string)=>{setProfile(p=>({...p,[key]:key==='min'||key==='max'?Math.max(0,Number(value)):value}));setSelected(new Set());};
 return <div className="app"><aside className="sidebar"><a className="brand" href="/"><span className="brand-icon"><Search size={23}/></span>LeadLens<span className="beta">BETA</span></a><div className="workspace"><span className="workspace-icon">K</span><div><strong>My workspace</strong><small>Lead intelligence</small></div></div><div className="nav-caption">WORKSPACE</div><button className={'nav '+(view==='all'?'active':'')} onClick={()=>{setView('all');setSelected(new Set());}}><Building2 size={19}/>All companies<span>{leads.length}</span></button><button className={'nav '+(view==='priority'?'active':'')} onClick={()=>{setView('priority');setSelected(new Set());}}><Target size={19}/>High priority<span>{high}</span></button><button className={'nav '+(view==='review'?'active':'')} onClick={()=>{setView('review');setSelected(new Set());}}><ShieldCheck size={19}/>Quality review<span>{review}</span></button><div className="sidebar-note"><Layers size={23}/><strong>Better data.<br/>Better conversations.</strong><p>Clean your list and focus on companies that fit.</p></div><div className="owner"><span className="avatar">KK</span><div><strong>Kranti Kumar</strong><small>Personal workspace</small></div></div></aside>
 <div className="main-shell"><header className="topbar"><div>Workspace <ChevronRight size={14}/><strong>Companies</strong></div><span className="private"><ShieldCheck size={15}/>Private workspace</span></header><main><div className="heading"><div><div className="eyebrow">YOUR NEXT CONVERSATION STARTS HERE</div><h1>Find the right fit.</h1><p>Turn a company list into a focused outreach shortlist.</p></div><div className="actions"><button onClick={download} disabled={!filtered.length||!!selected.size&&!filtered.some(l=>selected.has(l.id))}><Download size={17}/>Export {selected.size?'selected':'leads'}</button><button className="primary" onClick={()=>setImportOpen(true)}><Upload size={17}/>Import leads</button></div></div>
 {error&&<div className="message error" role="alert"><AlertCircle size={18}/>{error}<button onClick={()=>{setError('');load();}}>Retry</button><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
 {notice&&<div className="message" role="status"><Check size={18}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 {report&&<div className="message" role="status"><Check size={18}/><span>Import complete: <strong>{report.inserted} added</strong>, {report.duplicates} duplicates skipped, {report.rejected} rows rejected.</span><button aria-label="Dismiss import report" onClick={()=>setReport(null)}><X size={16}/></button></div>}
 <section className="metrics" aria-label="Lead overview"><div><span>Total companies<Building2 size={19}/></span><strong>{loading?'—':leads.length}</strong><small>Your saved lead collection</small></div><div><span>High priority<Target size={19}/></span><strong>{loading?'—':high}<em>80+ score</em></strong><small>Aligned with your target profile</small></div><div><span>Needs review<ShieldCheck size={19}/></span><strong>{loading?'—':review}</strong><small>Missing or incorrectly formatted data</small></div><div className="metric-blue"><span>Data completeness<Database size={19}/></span><strong>{leads.length?Math.round((leads.length-review)/leads.length*100):0}<b>%</b></strong><small>Companies with no quality flags</small></div></section>
 <section className="target-panel"><div className="target-title"><span className="target-icon"><SlidersHorizontal size={20}/></span><div><h2>Your target profile</h2><p>Change the criteria. Scores update instantly.</p></div></div><div className="target-fields"><label>Industry<input list="industries" value={profile.industry} onChange={e=>changeProfile('industry',e.target.value)} placeholder="Any industry"/><datalist id="industries">{['IT Services','Software','Cybersecurity','Consulting','Manufacturing',...new Set(leads.map(l=>l.industry))].filter((v,i,a)=>v&&a.indexOf(v)===i).map(x=><option key={x}>{x}</option>)}</datalist></label><label>Country<input list="countries" value={profile.country} onChange={e=>changeProfile('country',e.target.value)} placeholder="Any country"/><datalist id="countries">{['United States','Canada','United Kingdom','India',...new Set(leads.map(l=>l.country))].filter((v,i,a)=>v&&a.indexOf(v)===i).map(x=><option key={x}>{x}</option>)}</datalist></label><label>Employees<div className="range"><input aria-label="Minimum employees" type="number" min="0" value={profile.min} onChange={e=>changeProfile('min',e.target.value)}/><span>–</span><input aria-label="Maximum employees" type="number" min={profile.min} value={profile.max} onChange={e=>changeProfile('max',e.target.value)}/></div></label></div>{profile.min>profile.max&&<p className="range-error">Minimum employees exceeds maximum; no company will match size.</p>}</section>
 <section className="table-panel"><div className="table-title"><div><h2>{view==='priority'?'High-priority companies':view==='review'?'Companies needing review':'Company leads'}<span>{filtered.length}</span></h2><p>Ranked by fit. Click a company to see the reasoning.</p></div><button className="text-button" disabled={busy} onClick={sample}><RefreshCw size={15}/>{busy?'Importing…':'Load sample data'}</button></div><div className="toolbar"><div className="tabs" role="group" aria-label="Filter companies">{[['all','All leads'],['priority','High priority'],['review','Needs review']].map(([v,label])=><button className={view===v?'chosen':''} key={v} onClick={()=>{setView(v);setSelected(new Set());}}>{label}</button>)}</div><div className="table-controls"><label className="search"><Search size={16}/><input aria-label="Search companies" placeholder="Search companies…" value={query} onChange={e=>{setQuery(e.target.value);setSelected(new Set());}}/></label><select aria-label="Sort leads" value={sort} onChange={e=>setSort(e.target.value)}><option value="score">Highest score</option><option value="company">Company A–Z</option></select></div></div>
 <div className="table-scroll"><table><thead><tr><th className="check-cell"><input type="checkbox" aria-label="Select all visible leads" checked={!!filtered.length&&filtered.every(l=>selected.has(l.id))} onChange={e=>setSelected(e.target.checked?new Set(filtered.map(l=>l.id)):new Set())}/></th><th>COMPANY</th><th>INDUSTRY</th><th>LOCATION</th><th>SIZE</th><th>FIT SCORE</th><th>DATA QUALITY</th><th/></tr></thead><tbody>{filtered.map(l=>{const s=score(l,profile).total,q=quality(l);return <tr key={l.id} className={selected.has(l.id)?'selected':''}><td><input type="checkbox" aria-label={'Select '+l.company} checked={selected.has(l.id)} onChange={()=>toggle(l.id)}/></td><td><button className="company" onClick={()=>setDetail(l)}><span className={'company-icon tint-'+(l.company.length%4)}>{l.company.split(' ').slice(0,2).map(w=>w[0]).join('')}</span><span><strong>{l.company}</strong><small>{domain(l.website)||'No website provided'}</small></span></button></td><td>{l.industry||'Unknown'}</td><td>{l.city||'—'}<small>{l.country||'Unknown'}</small></td><td>{l.employees??'—'}<small>employees</small></td><td><span className={'score '+(s>=80?'high':s>=60?'medium':'low')}>{s}<span>/100</span></span><div className="score-track"><i style={{width:s+'%'}}/></div></td><td><span className={'badge '+(q.length?'warn':'good')}>{q.length?<AlertCircle size={13}/>:<Check size={13}/>} {q.length?`${q.length} ${q.length===1?'issue':'issues'}`:'Complete'}</span></td><td><button className="icon-button" aria-label={'View '+l.company} onClick={()=>setDetail(l)}><ChevronRight size={18}/></button></td></tr>;})}</tbody></table></div>
 {!filtered.length&&<div className="empty"><span><FileSpreadsheet size={30}/></span><h3>{loading?'Loading your companies…':leads.length?'No companies match':'Your shortlist starts with a list.'}</h3><p>{leads.length?'Try a different search or filter.':'Import your company CSV, or explore with 14 fictional sample rows.'}</p>{!loading&&(!leads.length?<button className="primary" disabled={busy} onClick={sample}>{busy?'Importing…':'Explore sample data'}</button>:<button onClick={()=>{setView('all');setQuery('');}}>Clear filters</button>)}</div>}
 <footer className="table-footer"><span>{selected.size?`${selected.size} selected · `:''}{filtered.length} of {leads.length} companies</span><span><ShieldCheck size={14}/>Email checks validate format, not deliverability.</span></footer></section><div className="page-foot"><span>LeadLens · Built for focused prospecting</span><span>Sample records are fictional. Scores are rule-based.</span></div></main></div>
 {importOpen&&<div className="overlay" onClick={()=>!busy&&setImportOpen(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="import-title" onClick={e=>e.stopPropagation()}><button ref={closeButton} className="close" aria-label="Close import" onClick={()=>setImportOpen(false)}><X/></button><span className="modal-icon"><Upload/></span><h2 id="import-title">Bring your leads together.</h2><p>Import a CSV to clean duplicates and score company fit.</p>{error&&<div className="message error" role="alert">{error}</div>}<div className="upload-zone"><FileSpreadsheet size={34}/><strong>Choose a company CSV</strong><p>Up to 1 MB · 1,000 rows per import</p><input ref={file} type="file" accept=".csv,text/csv" aria-label="Upload company CSV" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>1000000){setError('CSV limit is 1 MB.');return;}await importCsv(await f.text());}}}/></div><div className="import-help"><strong>One required column: company</strong><p>Also supported: website, industry, city, country, employees, email, source.</p><p>Same normalized website domain? The first saved record is kept. Without a domain, we compare company, city, and country.</p></div><div className="modal-actions"><a href="/template.csv" download>Download CSV template</a><button disabled={busy} onClick={sample}>{busy?'Importing…':'Use sample data'}</button></div></section></div>}
 {detail&&<div className="overlay detail-overlay" onClick={()=>setDetail(null)}><section className="drawer" role="dialog" aria-modal="true" aria-labelledby="detail-title" onClick={e=>e.stopPropagation()}><button ref={closeButton} className="close" aria-label="Close company details" onClick={()=>setDetail(null)}><X/></button><span className="modal-icon"><Building2/></span><h2 id="detail-title">{detail.company}</h2><p>{detail.city}{detail.city?', ':''}{detail.country}</p><div className="detail-score"><span>Target fit score<strong>{score(detail,profile).total}<small>/100</small></strong></span><Target size={42}/></div><h3>Why this score?</h3><p className="muted">A transparent rule-based score, not a prediction of conversion.</p><div className="reasons">{score(detail,profile).reasons.map(r=><div key={r.label}><span>{r.points?<Check size={16}/>:<span className="reason-dash">–</span>}{r.label}</span><strong>{r.points}<small> / {r.max}</small></strong></div>)}</div><h3>Company details</h3><dl><dt>Industry</dt><dd>{detail.industry||'Not provided'}</dd><dt>Employees</dt><dd>{detail.employees??'Unknown'}</dd><dt>Email</dt><dd>{detail.email||'Not provided'}</dd><dt>Website</dt><dd>{domain(detail.website)?<a href={'https://'+domain(detail.website)} target="_blank" rel="noopener noreferrer">{domain(detail.website)}<ArrowUpRight size={13}/></a>:'Not provided'}</dd><dt>Source</dt><dd>{detail.source}</dd></dl><h3>Data quality</h3>{quality(detail).length?<ul className="issues">{quality(detail).map(q=><li key={q}><AlertCircle size={15}/>{q}</li>)}</ul>:<p className="complete"><Check size={16}/>All checked fields are present and correctly formatted.</p>}<p className="muted">Contact information and website availability have not been independently verified.</p></section></div>}
 </div>;
}
